#!/usr/bin/env bash
#This script is used to transfer a file to the server
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
else
	path_to_file=$1
	ip=$2
	username=$3
	ssh_key=$4
	export SCP_OPTIONS="-o StrictHostKeyChecking=no"
	scp -i "$ssh_key" "$path_to_file" "$username@$ip":~/
fi
