#!/usr/bin/env bash
#This is used to install nginx web server
sudo apt update && apt -y install nginx
sudo ufw allow "Nginx HTTP"
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
