#!/usr/bin/env bash
# This script creates the file /var/run/myscript.pid
#+ containing its PID
#+ Displays "To infinity and beyond" indefinitely
#+ Displays "I hate the kill command" when receiving
#+ a SIGTERM signal
#+ Displays "Y U no love me?!" when receiving a SIGINT
#+ signal
#+ Deletes the file /var/run/myscript.pid and
#+ terminates itself when receiving a SIGQUIT or
#+ SIGTERM signal

pid=$$


file=/var/run/myscript.pid

touch $file

echo $pid > $file

trap 'echo "I hate the kill command" && work' SIGTERM

trap 'echo "Y U no love me ?!"' SIGINT

trap work SIGQUIT

function work ()
{
	rm "$file"
	exit
}
while true
do
	echo "To infinity and beyond"
	sleep 2
done
