#!/usr/bin/env bash
# Displays numbers from 1-100, where if:
#+ the number is a multiple of 3 and 5, display "FizzBuzz"
#+ the number is a multiple of 3, display "Fizz"
#+ the number is a multiple of 5, diplay "Buzz"

for i in {1..100}
do
	if ! ((i % 3)) && ! ((i % 5))
	then
		echo "FizzBuzz"
	elif ! ((i % 3))
	then
		echo "Fizz"
	elif ! ((i % 5))
	then
		echo "Buzz"
	else
		echo $i
	fi
done
