#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the ninth
#+ iteration, it diplays "Hi" instead

i=1

while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((i=i+1))
done
