#!/usr/bin/env bash
# The script diplays numbers from 1-20, it also diplays
#+ for the 4th iteration "bad luck from China", for the 9th
#+ iteration "bad luck from Japan" and for the 17th iteration
#+ "bad luck from Italy"

num=1

while [ $num -le 20 ]
do
	case $num in
		4)
			echo $num
			echo "bad luck from China"
			;;
		9)
			echo $num
			echo "bad luck from Japan"
			;;
		17)
			echo $num
			echo "bad luck from Italy"
			;;
		*)
			echo $num
			;;
	esac
	((num=num+1))
done
