#!/usr/bin/env bash
# The script displays time for 12 hours and 59 minutes
#+ hours diplayed from 0-12 and minutes from 1-59

hrs=0

while [ $hrs -le 12 ]
do
	mins=1
	if [ $hrs -eq 0 ]
	then
		echo "Hour: $hrs"
	else
		while [ $mins -le 60 ]
		do
			if [ $mins -eq 60 ]
			then
				echo "Hour: $hrs"
			else
				echo $mins
			fi
			((mins=mins+1))
		done
	fi
	((hrs=hrs+1))
done
mins=1
while [ $mins -lt 60 ]
do
	echo $mins
	((mins=mins+1))
done
