#!/usr/bin/env bash
# The script displays contents of the current directory
#+ they are in list format and only the part of the name
#+ after the first dash is displayed

files=$(ls)
for file in $files
do
	echo "$file" | cut -d "-" -f 2-
done
