#!/usr/bin/env bash
# The script gives information about the school file and prints
#+ "school file exist" - if it exists
#+ "school file does not exist" - if it doesn't exist
#+ "school file is empty" - if empty
#+ "school file is not empty" - if not empty
#+ "school is a regular file" -  if a regular file
#+ nothing - if not a regular file

if [ -e ./school ]
then
	echo "school file exists"
	if [ -s ./school ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f ./school ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
