#!/usr/bin/env bash
# This script installs ufw and sets it to accept incoming
#+ traffic on ports 22, 443 and 80, TCP
sudo apt update && sudo apt install -y ufw
sudo ufw --force enable
sudo sed -i 's/ENABLED=no/ENABLED=yes/g' /etc/ufw/ufw.conf
sudo ufw default deny
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
