#!/usr/bin/env bash
#This script sets the owner of nginx process and listening to port 8080
sudo adduser --system --no-create-home --disabled-login --disabled-password --group nginx
sudo sed -i 's/user www-data;/user nginx nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen\s*[::]:80;/listen [::]:8080;/g' /etc/nginx/sites-available/default
sudo service nginx restart
