#!/usr/bin/env bash
#This script sets the owner of nginx process and listening to port 8080
sudo sed -i 's/#user www-data;/user nginx nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen\s*80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen\s*[::]:80 default_server ipv6only=on;/listen [::]:8080 default_server ipv6only=on;/g' /etc/nginx/sites-available/default
sudo service nginx restart
