#!/usr/bin/env bash
# This script generates an RSA key pair that saves
#+ its private key in the current working directory
#+ in the file school and school.pub for the public
#+ key
ssh-keygen -P "betty" -t rsa -b 4096 -f school
